baseURL = 'https://example.org/' #https://mufabo.github.io/fmso
languageCode = 'en-us'
title = 'fatih macht sachen online'
theme = "hugo-theme-m10c"
author = 'M. Fatih Bostanci'
description = 'Here you can find my musings on various topics'
avatar = 'D:\fatihgithub.com\mufabo\fmso\static\1634299277238.jpeg'
favicon = 'D:\fatih\github.com\mufabo\fmso\static\1634299277238.jpeg'